name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

env:
  API_URL: ${{ secrets.API_URL }}
  AUDIVERIS_API_URL: ${{ secrets.AUDIVERIS_API_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start Flask (background) and wait for readiness
      run: |
        # start Flask in background on port 5000
        flask --app src/api/main.py run --host=127.0.0.1 --port=5000 &
        FLASK_PID=$!
        # wait up to 60s for the app to respond
        for i in $(seq 1 60); do
          if curl -sSf http://127.0.0.1:5000/app-health >/dev/null; then
            echo "Flask is up"
            break
          fi
          sleep 1
        done
        # optionally fail if not up
        if ! curl -sSf http://127.0.0.1:5000/app-health >/dev/null; then
          echo "Flask did not start in time" >&2
          kill $FLASK_PID || true
          exit 1
        fi
    - name: Test with pytest
      run: |
        python -m pytest -q